# Generated by Django 3.2.19 on 2023-06-26 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='color',
            field=models.CharField(choices=[('A', 'Azul'), ('Am', 'Amarillo'), ('N', 'Negro'), ('B', 'Blanco'), ('R', 'Rosa')], max_length=50),
        ),
    ]
