# Generated by Django 3.2.19 on 2023-05-30 13:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MakeupProduct',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('active', models.BooleanField(default=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stock', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('trademark', models.CharField(max_length=50)),
                ('color', models.CharField(choices=[('R', 'Rojo'), ('A', 'Azul'), ('Am', 'Amarillo'), ('N', 'Negro'), ('P', 'Plateado'), ('B', 'Blanco'), ('D', 'Dorado')], max_length=50)),
                ('price', models.IntegerField()),
            ],
            options={
                'verbose_name': 'MakeupProduct',
                'verbose_name_plural': 'MakeupProducts',
                'ordering': ['-created_at'],
            },
        ),
    ]
