# Generated by Django 3.2.19 on 2023-05-18 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makeup_product', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='makeupproduct',
            options={'ordering': ['-created_at'], 'verbose_name': 'MakeupProduct', 'verbose_name_plural': 'MakeupProducts'},
        ),
        migrations.AlterField(
            model_name='makeupproduct',
            name='color',
            field=models.CharField(choices=[('R', 'Rojo'), ('A', 'Azul'), ('Am', 'Amarillo'), ('N', 'Negro'), ('P', 'Plateado'), ('B', 'Blanco'), ('D', 'Dorado')], max_length=50),
        ),
        migrations.AlterField(
            model_name='makeupproduct',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='makeupproduct',
            name='trademark',
            field=models.CharField(max_length=50),
        ),
    ]
