# Generated by Django 3.2.19 on 2023-05-22 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makeup_product', '0002_auto_20230518_2221'),
    ]

    operations = [
        migrations.AddField(
            model_name='makeupproduct',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='makeupproduct',
            name='deleted_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
