# Generated by Django 3.2.19 on 2023-06-28 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makeup_product', '0002_makeupproduct_user'),
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favorites',
            field=models.ManyToManyField(related_name='favorites_by', to='makeup_product.MakeupProduct'),
        ),
    ]
