# Generated by Django 3.2.19 on 2023-06-28 19:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('makeup_product', '0002_makeupproduct_user'),
        ('authentication', '0002_user_favorites'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('active', models.BooleanField(default=True)),
                ('text', models.CharField(max_length=200)),
                ('MakeupProduct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='makeup_product.makeupproduct')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'MakeupProduct', 'text')},
            },
        ),
        migrations.AddField(
            model_name='user',
            name='comments',
            field=models.ManyToManyField(related_name='comment_by', through='authentication.Comment', to='makeup_product.MakeupProduct'),
        ),
    ]
