# Generated by Django 3.2.19 on 2023-06-06 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nevera',
            name='marca',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='nevera',
            name='nombre',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
