# Generated by Django 3.2.19 on 2023-06-06 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0003_auto_20230606_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nevera',
            name='marca',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='nevera',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
